train:
  epochs: 1000
  eval_freq: 10

data:
  _class: ese.datasets.OCTA_6M
  in_channels: 1
  out_channels: 1 
  label: 255 # Two options, 100 and 255 (center or vessels)
  version: 1.0 # Two options, 0.1 and 1.0 (128x128 or 400x400 res)
  label_threshold: 0.5 # The default is to train on hard labels.
  iters_per_epoch: 1000 
  preload: False 

dataloader:
  batch_size: 8

model:
  dims: 2

log:
  checkpoint_freq: 50
  root: '?'
  metrics:
    dice_score:
      _fn: ionpy.metrics.dice_score
      batch_reduction: 'mean' 
      ignore_empty_labels: False 
      from_logits: True
    ece_loss:
      _fn: ese.metrics.image_ece_loss
      num_prob_bins: 15
      from_logits: True
    area_estimation_error:
      _fn: ese.losses.area_estimation_error
      from_logits: True
      square_diff: False