log:
  track_label_amounts: True
  min_fg_pixels: 0

data:
  input_type: image 

global_calibration:
    num_classes: 19

qual_metrics:
    - Dice:
        _fn: ese.metrics.dice_score
        from_logits: True
        batch_reduction: 'mean' 
        ignore_empty_labels: True
        metric_type: quality
    - HD95:
        _fn: ese.metrics.hd95
        from_logits: True
        batch_reduction: 'mean' 
        ignore_empty_labels: True
        metric_type: quality
    - BoundaryIOU:
        _fn: ese.metrics.boundary_iou
        boundary_width: 2
        from_logits: True
        batch_reduction: 'mean' 
        ignore_empty_labels: True 
        metric_type: quality

augmentations:
    - Resize:
        height: 256
        width: 512