log:
  track_label_amounts: True 

inference_data:
  split: '?'
  label: 255
  version: 1.0
  input_type: image 
  label_threshold: 0.5
  return_gt_proportion: True

global_calibration:
    num_classes: 1

model:
    pred_label: 0 # We do this for binary predictions.

qual_metrics:
    - Dice:
        _fn: ese.metrics.dice_score
        batch_reduction: 'mean' 
        ignore_empty_labels: False
        metric_type: quality
    - HD95:
        _fn: ese.metrics.hd95
        batch_reduction: 'mean' 
        ignore_empty_labels: False
        metric_type: quality
    - BoundaryIOU:
        _fn: ese.metrics.boundary_iou
        boundary_width: 4
        batch_reduction: 'mean' 
        ignore_empty_labels: False 
        metric_type: quality