experiment: 
    inf_kwargs:
        from_logits: True
        threshold: 0.5 
        temperature: 1.0
        pred_patch_dims: # We need to do patch based inference because native res is 1500x1500
            height: 500 
            width: 500
log:
  track_label_amounts: True 

inference_data:
  split: '?'
  label: 255
  version: 1.0
  label_threshold: 0.5
  return_gt_proportion: True

global_calibration:
    num_classes: 1

qual_metrics:
    - Dice:
        _fn: ese.metrics.dice_score
        batch_reduction: 'mean' 
        ignore_empty_labels: False
        metric_type: quality