log:
  track_label_amounts: True 

experiment:
  num_supports: 5
  
inference_data:
  resolution: 128 

global_calibration:
    num_classes: 1

qual_metrics:
    - Dice:
        _fn: ese.metrics.dice_score
        batch_reduction: 'mean' 
        ignore_empty_labels: False
        metric_type: quality