log:
  track_label_amounts: True 

inference_data:
  split: '?'
  resolution: 256
  input_type: image 
  label: 0

global_calibration:
    num_classes: 1

model:
    pred_label: 0 # We do this for binary predictions.

qual_metrics:
    - Dice:
        _fn: ese.metrics.dice_score
        batch_reduction: 'mean' 
        ignore_empty_labels: False
        metric_type: quality