log:
  track_label_amounts: True 
  min_fg_pixels: 0

data:
  input_type: image 
  subsplit: '0'

global_calibration:
    num_classes: 2

qual_metrics:
    - Dice:
        _fn: ese.metrics.dice_score
        from_logits: True
        batch_reduction: 'mean' 
        ignore_index: 0
        metric_type: quality
    - HD95:
        _fn: ese.metrics.hd95
        from_logits: True
        batch_reduction: 'mean' 
        ignore_index: 0
        metric_type: quality
    - BoundaryIOU:
        _fn: ese.metrics.boundary_iou
        boundary_width: 1
        from_logits: True
        batch_reduction: 'mean' 
        metric_type: quality
    - Accuracy:
        _fn: ionpy.metrics.segmentation.pixel_accuracy
        from_logits: True
        metric_type: quality
    - Recall:
        _fn: ionpy.metrics.segmentation.pixel_recall
        from_logits: True
        metric_type: quality
    - Precision:
        _fn: ionpy.metrics.segmentation.pixel_precision
        from_logits: True
        metric_type: quality