experiment:
  slices_per_fp: 5

dataloader:
  batch_size: 2
  num_workers: 1

inference_data:
  input_type: volume
  slicing: full 
  num_slices: 1
  annotator: '?'
  split: '?'
  task: '?' 

global_calibration:
    num_classes: 1

log:
  track_label_amounts: True 
  min_fg_pixels: 1

model:
    pred_label: 0

qual_metrics:
    - Dice:
        _fn: ese.metrics.dice_score
        batch_reduction: 'mean' 
        ignore_empty_labels: False
        metric_type: quality