experiment:
  slices_per_fp: 5

dataloader:
  batch_size: 2
  num_workers: 1

inference_data:
  input_type: volume
  slicing: full 
  num_slices: 1
  annotator: '?'
  split: '?'
  task: '?' 

global_calibration:
    num_classes: 1

log:
  track_label_amounts: True 
  min_fg_pixels: 1

model:
    pred_label: 0

qual_metrics:
    - Dice:
        _fn: ese.metrics.dice_score
        batch_reduction: 'mean' 
        ignore_empty_labels: False
        metric_type: quality
    - HD95:
        _fn: ese.metrics.hd95
        batch_reduction: 'mean' 
        ignore_empty_labels: False
        metric_type: quality
    - BoundaryIOU:
        _fn: ese.metrics.boundary_iou
        boundary_width: 4
        batch_reduction: 'mean' 
        ignore_empty_labels: False 
        metric_type: quality
    - Accuracy:
        _fn: ese.metrics.pixel_accuracy
        metric_type: quality
    - SoftVolumeError:
        _fn: ese.metrics.volume_error
        do_threshold: False 
        batch_reduction: 'mean' 
        metric_type: quality
    - HardVolumeError:
        _fn: ese.metrics.volume_error
        do_threshold: True
        threshold: 0.5
        batch_reduction: 'mean' 
        metric_type: quality