# For calibration methods.
Finetune:
  _class: null
  
TempScaling:
  _class: ese.models.calibrators.Temperature_Scaling

ImageBasedTS:
  _class: ese.models.calibrators.ImageBasedTS
  img_channels: 1
  num_classes: 1

LTS:
  _class: ese.models.calibrators.LocalTS
  img_channels: 1
  num_classes: 1
  filters:
    - 4 
    - 4 
    - 4 

# For calibration methods.
PopcornScaling:
  _class: ese.models.calibrators.Popcorn_Scaling
  ksize: 5 
  init_mode: random 