data:
  _class: ese.datasets.ISLES
  in_channels: 1
  out_channels: 1 
  version: '?' # Two options, 0.1 and 1.0 either 128 or 400 res 
  preload: False 

dataloader:
  batch_size: 1
  num_workers: 1

log:
  root: '?'
  checkpoint_freq: 20 
  metrics:
    dice_score:
      _fn: ionpy.metrics.dice_score
      batch_reduction: 'mean' 
      ignore_empty_labels: False 
      from_logits: True
    ece_loss:
      _fn: ese.metrics.image_ece_loss
      num_prob_bins: 15
      from_logits: True
    edge_ece_loss:
      _fn: ese.metrics.image_edge_ece_loss
      num_prob_bins: 15
      neighborhood_width: 3
      from_logits: True

model:
  filters: [64, 64, 64, 64, 64]
  convs_per_block: 3
  dims: 3

train:
  epochs: 50
  eval_freq: 5 
